name: Release

on:
  push:
    branches:
      - Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Visual Studio
        uses: microsoft/setup-msbuild@v1
        with:
          vs-version: '2022'  # Указываем конкретную версию Visual Studio

      - name: Configure CMake
        run: |
          cmd /c "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
          cmake -S . -B build -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cmd /c "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
          cmake --build build --config Release

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.0
          release_name: Release v1.0.0
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          upload_artifact: true
          asset_path: build/bin/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}